
[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "serif"

[server]
headless = true
port = 8501
enableCORSProtection = false
maxUploadSize = 1024

[browser]
gatherUsageStats = false
showErrorDetails = false
